export type MediaCategory =
  | 'all'
  | 'sermons'
  | 'hymns'
  | 'heritage-videos';

export interface ArchiveItem {
  title?: string;
  copticTitle?: string;
  part?: number;
  copticSuffix?: string;
  subtitle: string;
  category: MediaCategory;
  videoId: string;
  thumbnail: string;
  watchUrl: string;
  source: 'channel' | 'manual';
  useCopticFont?: boolean;
}

export const ARCHIVE_ITEMS: ArchiveItem[] = [
    {
title: 'Divine Liturgy and Celebration: Priesthood Ordination of Fr. Boutros Boutros and Fr. Boules Mikhail (February 16, 1997)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: 'AAVqbo9GdFY',
thumbnail: 'https://img.youtube.com/vi/AAVqbo9GdFY/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=AAVqbo9GdFY',
source: 'manual',
},
{
title: 'Divine Liturgy: Fr. Boutros Boutros at St. Mary El-Sourian Monastery (March 24, 1997)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: 'T5_Q0d353kw',
thumbnail: 'https://img.youtube.com/vi/T5_Q0d353kw/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=T5_Q0d353kw',
source: 'manual',
},
{
title: 'Reception Prayer and Receiving of Fr. Boutros Boutros to Nashville, TN (April 4, 1997)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: 'EnrcVgEGT4w',
thumbnail: 'https://img.youtube.com/vi/EnrcVgEGT4w/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=EnrcVgEGT4w',
source: 'manual',
},
{
title: 'First Divine Liturgy for Fr. Boutros Boutros in Nashville, TN (April 5, 1997)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: 'iH701rcVwMo',
thumbnail: 'https://img.youtube.com/vi/iH701rcVwMo/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=iH701rcVwMo',
source: 'manual',
},
{
title: 'Glorious Nativity Feast with His Eminence Metropolitan Youssef (January 6, 1998)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: '4kLCC0P-hGI',
thumbnail: 'https://img.youtube.com/vi/4kLCC0P-hGI/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=4kLCC0P-hGI',
source: 'manual',
},
{
title: 'St. Mina Church Consecration and the Priesthood Ordination of the Reposed Fr. Mina Iskander (August 27, 2000)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: 'nwdAm9pIlXw',
thumbnail: 'https://img.youtube.com/vi/nwdAm9pIlXw/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=nwdAm9pIlXw',
source: 'manual',
},
{
title: 'His Holiness Pope Tawadros II | Benediction Prayer and Visit to St. Clement Academy (October 9, 2015)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: 'rY_c_VhJslA',
thumbnail: 'https://img.youtube.com/vi/rY_c_VhJslA/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=rY_c_VhJslA',
source: 'manual',
},
{
title: 'Divine Liturgy with His Grace Bishop Peter (December 18, 2016)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: '1c04bY6C2a4',
thumbnail: 'https://i.postimg.cc/m2J0yRNX/2016.png',
watchUrl: 'https://www.youtube.com/watch?v=1c04bY6C2a4',
source: 'manual',
},
{
title: 'Divine Liturgy: Hegumen Elevation of Fr. Boutros Boutros (February 5, 2017)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: 'Fw08GjO5S_g',
thumbnail: 'https://img.youtube.com/vi/Fw08GjO5S_g/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=Fw08GjO5S_g',
source: 'manual',
},
{
title: 'Divine Liturgy with His Grace Bishop Basil (June 22, 2019)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: 'Xx9PKoo4d-k',
thumbnail: 'https://i.postimg.cc/x8k6XJ7V/2019.png',
watchUrl: 'https://www.youtube.com/watch?v=Xx9PKoo4d-k',
source: 'manual',
},
{
title: 'St. Mina Renovated Church Consecration (November 28, 2022)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: 'Vhnyzn_fUvY',
thumbnail: 'https://img.youtube.com/vi/Vhnyzn_fUvY/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=Vhnyzn_fUvY',
source: 'manual',
},
{
title: 'Divine Liturgy with His Grace Bishop Theophilus (May 12, 2023)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: '2doI6w8t0LA',
thumbnail: 'https://i.postimg.cc/jjw9W1JB/Add-a-subheading-(4).png',
watchUrl: 'https://www.youtube.com/watch?v=2doI6w8t0LA',
source: 'manual',
},
{
title: 'Divine Liturgy with His Eminence Metropolitan Thomas (April 7, 2024)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: 'lDqgzbA8WMs',
thumbnail: 'https://i.postimg.cc/bNrRNtnx/2024-(1).png',
watchUrl: 'https://www.youtube.com/watch?v=lDqgzbA8WMs',
source: 'manual',
},
{
title: 'Divine Liturgy with His Grace Bishop Theophilus (May 24, 2024)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: 'KdoxQJltzE8',
thumbnail: 'https://i.postimg.cc/4dX6C7ZV/2024-(2).png',
watchUrl: 'https://www.youtube.com/watch?v=KdoxQJltzE8',
source: 'manual',
},
{
title: 'Divine Liturgy with His Grace Bishop Philopateer (July 7, 2024)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: 'rZ0TFMyhBcM',
thumbnail: 'https://i.postimg.cc/T3YsfFPL/2024-(3).png',
watchUrl: 'https://www.youtube.com/watch?v=rZ0TFMyhBcM',
source: 'manual',
},
{
title: 'Divine Liturgy with His Eminence Metropolitan Youssef and His Grace Bishop Daniel (October 7, 2024)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: '5R4aFfQugts',
thumbnail: 'https://img.youtube.com/vi/5R4aFfQugts/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=5R4aFfQugts',
source: 'manual',
},
{
title: 'Divine Liturgy: Deacon Ordination of Fr. Kyrillos Zaki (August 23, 2025)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: 'lQeZJqXBE9M',
thumbnail: 'https://img.youtube.com/vi/lQeZJqXBE9M/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=lQeZJqXBE9M',
source: 'manual',
},
{
title: 'Vespers and Midnight Praises with H.E.M. Youssef, H.E.M. Youannes, H.G.B. Basil, & H.G.B. Gregory (August 23, 2025)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: 'MPSvz4LM3IQ',
thumbnail: 'https://img.youtube.com/vi/MPSvz4LM3IQ/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=MPSvz4LM3IQ',
source: 'manual',
},
{
title: 'Divine Liturgy: Priesthood Ordination of Fr. Kyrillos Zaki (August 24, 2025)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: 'x0Y6pwzDqqM',
thumbnail: 'https://img.youtube.com/vi/x0Y6pwzDqqM/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=x0Y6pwzDqqM',
source: 'manual',
},
{
title: 'Reception Prayer for Fr. Kyrillos Zaki (October 3, 2025)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: 'B9ulu9Jc-sc',
thumbnail: 'https://img.youtube.com/vi/B9ulu9Jc-sc/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=B9ulu9Jc-sc',
source: 'manual',
},
{
title: 'Vespers and Bible Study with His Grace Bishop Elarion (October 4, 2025)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: 'V__30MVDPjg',
thumbnail: 'https://i.postimg.cc/prKDNWj6/2025.png',
watchUrl: 'https://www.youtube.com/watch?v=V__30MVDPjg',
source: 'manual',
},
{
title: 'Vespers with His Eminence Metropolitan Antonious (November 28, 2025)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: 'OP_AHRwWXYs',
thumbnail: 'https://img.youtube.com/vi/OP_AHRwWXYs/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=OP_AHRwWXYs',
source: 'manual',
},
{
title: 'Divine Liturgy with His Eminence Metropolitan Antonious (November 29, 2025)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: '_JJGD2OFaMQ',
thumbnail: 'https://img.youtube.com/vi/_JJGD2OFaMQ/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=_JJGD2OFaMQ',
source: 'manual',
},
{
title: 'Divine Liturgy with His Eminence Metropolitan Bessada (December 21, 2025)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: 'HLkW6Qb4UzM',
thumbnail: 'https://i.postimg.cc/Gtp1V26t/anba-bessada.png',
watchUrl: 'https://www.youtube.com/watch?v=HLkW6Qb4UzM',
source: 'manual',
},
{
title: 'Divine Liturgy with His Grace Bishop Raphael (April 26, 2026)',
subtitle: 'Heritage Video',
category: 'heritage-videos',
videoId: 'D49PwNwuL_U',
thumbnail: 'https://i.postimg.cc/J7j6CMRr/anba-raphael.png',
watchUrl: 'https://www.youtube.com/watch?v=D49PwNwuL_U',
source: 'manual',
},
{
title: 'Coptic Deacon Responses',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'Wb9QBeSo3o0',
thumbnail: 'https://img.youtube.com/vi/Wb9QBeSo3o0/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=Wb9QBeSo3o0',
source: 'manual',
},
{
title: 'Vesper Praises: Ⲛⲓⲉⲑⲛⲟⲥ ⲧⲏⲣⲟⲩ (Part 1)',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'GyHISTEfWFI',
thumbnail: 'https://img.youtube.com/vi/GyHISTEfWFI/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=GyHISTEfWFI',
source: 'manual',
},
{
title: 'Vesper Praises: Ⲛⲓⲉⲑⲛⲟⲥ ⲧⲏⲣⲟⲩ (Part 2)',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'N5DiOHWpF0Q',
thumbnail: 'https://img.youtube.com/vi/N5DiOHWpF0Q/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=N5DiOHWpF0Q',
source: 'manual',
},
{
title: 'Vesper Praises: Watos Psali for the Virgin Mary (Coptic)',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'rgUtxy_dtcM',
thumbnail: 'https://img.youtube.com/vi/rgUtxy_dtcM/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=rgUtxy_dtcM',
source: 'manual',
},
{
title: 'Vesper Praises: Saturday Watos Psali (Coptic)',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'C3iIzZMzzQc',
thumbnail: 'https://img.youtube.com/vi/C3iIzZMzzQc/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=C3iIzZMzzQc',
source: 'manual',
},
{
title: 'Vesper Praises: Saturday Theotokia (Coptic)',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'FgiV1rTu0xk',
thumbnail: 'https://img.youtube.com/vi/FgiV1rTu0xk/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=FgiV1rTu0xk',
source: 'manual',
},
{
title: 'Introduction to the Midnight Praises (Ⲧⲉⲛⲑⲏⲛⲟⲩ) | Part 1',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'DVOFb8kkuWQ',
thumbnail: 'https://img.youtube.com/vi/DVOFb8kkuWQ/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=DVOFb8kkuWQ',
source: 'manual',
},
{
title: 'Introduction to the Midnight Praises (Ⲧⲉⲛⲑⲏⲛⲟⲩ) | Part 2',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'tdddwKee3qE',
thumbnail: 'https://img.youtube.com/vi/tdddwKee3qE/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=tdddwKee3qE',
source: 'manual',
},
{
title: 'Midnight Praises: Ϩⲱⲥ ⲉⲣⲟϥ (Part 1)',
subtitle: 'Hymns',
category: 'hymns',
videoId: '7Yc0zGaugYA',
thumbnail: 'https://img.youtube.com/vi/7Yc0zGaugYA/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=7Yc0zGaugYA',
source: 'manual',
},
{
title: 'Midnight Praises: Ϩⲱⲥ ⲉⲣⲟϥ (Part 2)',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'U5oFT2GB_iM',
thumbnail: 'https://img.youtube.com/vi/U5oFT2GB_iM/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=U5oFT2GB_iM',
source: 'manual',
},
{
title: 'Alleluia of the Late Afternoon (Melismatic Ending of the Fourth Canticle)',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'Sh3EI2pLFmQ',
thumbnail: 'https://img.youtube.com/vi/Sh3EI2pLFmQ/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=Sh3EI2pLFmQ',
source: 'manual',
},
{
title: 'Melismatic Ending of the Sunday Theotokia 15 (Ⲉⲃⲟⲗϩⲓⲧⲉⲛ) | Part 1',
subtitle: 'Hymns',
category: 'hymns',
videoId: '3Bdd63L7voc',
thumbnail: 'https://img.youtube.com/vi/3Bdd63L7voc/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=3Bdd63L7voc',
source: 'manual',
},
{
title: 'Melismatic Ending of the Sunday Theotokia 15 (Ⲉⲃⲟⲗϩⲓⲧⲉⲛ) | Part 2',
subtitle: 'Hymns',
category: 'hymns',
videoId: '_FkbQVLXMbE',
thumbnail: 'https://img.youtube.com/vi/_FkbQVLXMbE/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=_FkbQVLXMbE',
source: 'manual',
},
{
title: 'Long Singary Psalm (Festal Hymn)',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'BiUmK8iL8YA',
thumbnail: 'https://img.youtube.com/vi/BiUmK8iL8YA/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=BiUmK8iL8YA',
source: 'manual',
},
{
title: 'Hymn of the Cross (Ⲫⲁⲓ ̀ⲉⲧⲁϥⲉⲛϥ)',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'Sxa8tEwT6ak',
thumbnail: 'https://img.youtube.com/vi/Sxa8tEwT6ak/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=Sxa8tEwT6ak',
source: 'manual',
},
{
title: 'Kiahk Hymns Review (Part 1)',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'm8mh6w0o-7w',
thumbnail: 'https://img.youtube.com/vi/m8mh6w0o-7w/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=m8mh6w0o-7w',
source: 'manual',
},
{
title: 'Kiahk Hymns Review (Part 2)',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'ip2cmW_33tE',
thumbnail: 'https://img.youtube.com/vi/ip2cmW_33tE/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=ip2cmW_33tE',
source: 'manual',
},
{
title: 'Standard Adam Aspasmos (Ⲟⲩⲛⲟϥ ̀ⲙⲙⲟ Ⲙⲁⲣⲓⲁ)',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'dG1GMXkGtms',
thumbnail: 'https://img.youtube.com/vi/dG1GMXkGtms/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=dG1GMXkGtms',
source: 'manual',
},
{
title: 'Greet One Another - Great (Ⲁⲥⲡⲁⲍⲉⲥⲑⲉ)',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'g5_0oiJtWm0',
thumbnail: 'https://img.youtube.com/vi/g5_0oiJtWm0/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=g5_0oiJtWm0',
source: 'manual',
},
{
title: 'Feast of Nativity Hymns Review',
subtitle: 'Hymns',
category: 'hymns',
videoId: '4twTc22q6Ys',
thumbnail: 'https://img.youtube.com/vi/4twTc22q6Ys/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=4twTc22q6Ys',
source: 'manual',
},
{
title: 'The Wednesday Theotokia 7 | Galilee of the Gentiles (Ϯⲅⲁⲗⲓⲗⲉ̀ⲁ) | Part 1',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'xbrwToYbeoo',
thumbnail: 'https://img.youtube.com/vi/xbrwToYbeoo/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=xbrwToYbeoo',
source: 'manual',
},
{
title: 'The Wednesday Theotokia 7 | Galilee of the Gentiles (Ϯⲅⲁⲗⲓⲗⲉ̀ⲁ) | Part 2',
subtitle: 'Hymns',
category: 'hymns',
videoId: '6gVGYW3kNts',
thumbnail: 'https://img.youtube.com/vi/6gVGYW3kNts/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=6gVGYW3kNts',
source: 'manual',
},
{
title: 'The Wednesday Theotokia 7 | Galilee of the Gentiles (Ϯⲅⲁⲗⲓⲗⲉ̀ⲁ) | Part 3',
subtitle: 'Hymns',
category: 'hymns',
videoId: '6R7-rfkdJT4',
thumbnail: 'https://img.youtube.com/vi/6R7-rfkdJT4/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=6R7-rfkdJT4',
source: 'manual',
},
{
title: 'Great Lent Hymns Review',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'lH0eCUvHAb0',
thumbnail: 'https://img.youtube.com/vi/lH0eCUvHAb0/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=lH0eCUvHAb0',
source: 'manual',
},
{
title: 'Psalm 150 for Great Lent and Palm Sunday',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'IsGt2k0jw34',
thumbnail: 'https://img.youtube.com/vi/IsGt2k0jw34/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=IsGt2k0jw34',
source: 'manual',
},
{
title: 'Great Friday Hymns Review (Part 1)',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'OvFN3Fz7u44',
thumbnail: 'https://img.youtube.com/vi/OvFN3Fz7u44/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=OvFN3Fz7u44',
source: 'manual',
},
{
title: 'Great Friday Hymns Review (Part 2)',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'TkxTmT24fXM',
thumbnail: 'https://img.youtube.com/vi/TkxTmT24fXM/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=TkxTmT24fXM',
source: 'manual',
},
{
title: 'O Only-Begotten Son (Ⲟⲙⲟⲛⲟⲅⲉⲛⲏⲥ) | Part 1',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'Rcg71JMsr30',
thumbnail: 'https://img.youtube.com/vi/Rcg71JMsr30/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=Rcg71JMsr30',
source: 'manual',
},
{
title: 'O Only-Begotten Son (Ⲟⲙⲟⲛⲟⲅⲉⲛⲏⲥ) | Part 2',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'knUeH-XDwr8',
thumbnail: 'https://img.youtube.com/vi/knUeH-XDwr8/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=knUeH-XDwr8',
source: 'manual',
},
{
title: 'Hymn of the Censer (Ϯϣⲟⲩⲣⲏ) | Great Friday (9th Hour)',
subtitle: 'Hymns',
category: 'hymns',
videoId: '7x1C7pRJVew',
thumbnail: 'https://img.youtube.com/vi/7x1C7pRJVew/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=7x1C7pRJVew',
source: 'manual',
},
{
title: 'Bright Saturday and Resurrection Hymns Review',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'dmSs92064YE',
thumbnail: 'https://img.youtube.com/vi/dmSs92064YE/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=dmSs92064YE',
source: 'manual',
},
{
title: 'Third Greek Hymn for the Resurrection Procession (Ⲧⲏⲛ ̀ⲁⲛⲁⲥⲧⲁⲥⲓⲛ)',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'dps0rNWPASU',
thumbnail: 'https://img.youtube.com/vi/dps0rNWPASU/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=dps0rNWPASU',
source: 'manual',
},
{
title: 'Adam Exposition for the Feast of the Resurrection (Ϭⲓⲟⲩⲱⲓⲛⲓ)',
subtitle: 'Hymns',
category: 'hymns',
videoId: '6oPrYN0Bgsc',
thumbnail: 'https://img.youtube.com/vi/6oPrYN0Bgsc/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=6oPrYN0Bgsc',
source: 'manual',
},
{
title: 'All the Choirs (Ⲕⲁⲧⲁ ⲛⲓⲭⲟⲣⲟⲥ) | Complete Hymn',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'gbjrLFZ2Ar4',
thumbnail: 'https://img.youtube.com/vi/gbjrLFZ2Ar4/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=gbjrLFZ2Ar4',
source: 'manual',
},
{
title: 'Feast of Ascension Hymns Review',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'fTvuU3e7y2A',
thumbnail: 'https://img.youtube.com/vi/fTvuU3e7y2A/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=fTvuU3e7y2A',
source: 'manual',
},
{
title: 'Feast of Pentecost Hymns Review',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'fQL7kCv0fI0',
thumbnail: 'https://img.youtube.com/vi/fQL7kCv0fI0/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=fQL7kCv0fI0',
source: 'manual',
},
{
title: 'Apostles Fast Hymn (Ⲛⲓⲣⲱⲙⲓ) | Part 1',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'f-khSI2DBlI',
thumbnail: 'https://img.youtube.com/vi/f-khSI2DBlI/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=f-khSI2DBlI',
source: 'manual',
},
{
title: 'Apostles Fast Hymn (Ⲛⲓⲣⲱⲙⲓ) | Part 2',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'jV1XBVw6eVw',
thumbnail: 'https://img.youtube.com/vi/jV1XBVw6eVw/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=jV1XBVw6eVw',
source: 'manual',
},
{
title: 'Apostles Fast Hymn (̀Ⲛⲑⲱⲧⲉⲛ ⲇⲉ) | Part 1',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'M-uXBmoff-o',
thumbnail: 'https://img.youtube.com/vi/M-uXBmoff-o/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=M-uXBmoff-o',
source: 'manual',
},
{
title: 'Apostles Fast Hymn (̀Ⲛⲑⲱⲧⲉⲛ ⲇⲉ) | Part 2',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'p0sfzlAYFH0',
thumbnail: 'https://img.youtube.com/vi/p0sfzlAYFH0/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=p0sfzlAYFH0',
source: 'manual',
},
{
title: 'Apostles Fast Hymn (̀Ⲛⲑⲱⲧⲉⲛ ⲇⲉ) | Part 3',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'pL99woGTvl4',
thumbnail: 'https://img.youtube.com/vi/pL99woGTvl4/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=pL99woGTvl4',
source: 'manual',
},
{
title: 'Veneration Hymns: Rejoice O Theotokos (Ⲭⲉⲣⲉ ⲑⲉ̀ⲟⲧⲟⲕⲉ) | Part 1',
subtitle: 'Hymns',
category: 'hymns',
videoId: '_fgAUllT4dw',
thumbnail: 'https://img.youtube.com/vi/_fgAUllT4dw/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=_fgAUllT4dw',
source: 'manual',
},
{
title: 'Veneration Hymns: Rejoice O Theotokos (Ⲭⲉⲣⲉ ⲑⲉ̀ⲟⲧⲟⲕⲉ) | Part 2',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'xxJFXjPhrLM',
thumbnail: 'https://img.youtube.com/vi/xxJFXjPhrLM/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=xxJFXjPhrLM',
source: 'manual',
},
{
title: 'Veneration Hymns: Rejoice O Theotokos (Ⲭⲉⲣⲉ ⲑⲉ̀ⲟⲧⲟⲕⲉ) | Part 3',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'pSZI6rg6KYE',
thumbnail: 'https://img.youtube.com/vi/pSZI6rg6KYE/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=pSZI6rg6KYE',
source: 'manual',
},
{
title: 'Vespers Psalm for St. Mary`s Feast (Ϫⲉ ⲁⲩⲥⲁϫⲓ) | Part 1',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'vN5-_EJoTm4',
thumbnail: 'https://img.youtube.com/vi/vN5-_EJoTm4/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=vN5-_EJoTm4',
source: 'manual',
},
{
title: 'Vespers Psalm for St. Mary`s Feast (Ϫⲉ ⲁⲩⲥⲁϫⲓ) | Part 2',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'UCGBNYmOKwI',
thumbnail: 'https://img.youtube.com/vi/UCGBNYmOKwI/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=UCGBNYmOKwI',
source: 'manual',
},
{
title: 'Offering of the Lamb Hymn for St. Mary (Ⲭⲉⲣⲉ Ⲙⲁⲣⲓⲁ)',
subtitle: 'Hymns',
category: 'hymns',
videoId: '4U0U0YppPbs',
thumbnail: 'https://img.youtube.com/vi/4U0U0YppPbs/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=4U0U0YppPbs',
source: 'manual',
},
{
title: 'Standard Praxis Response (Ⲭⲉⲣⲉ ⲛⲉ Ⲙⲁⲣⲓⲁ) | Complete Hymn',
subtitle: 'Hymns',
category: 'hymns',
videoId: '4frZ_gDYeJw&t=1055s',
thumbnail: 'https://img.youtube.com/vi/4frZ_gDYeJw/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=4frZ_gDYeJw&t=1055s',
source: 'manual',
},
{
title: 'Hymn of the Ten Strings (Ⲁ ⲧⲁⲓ ⲡⲁⲣⲑⲉⲛⲟⲥ)',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'aKnS6onh8Ow',
thumbnail: 'https://img.youtube.com/vi/aKnS6onh8Ow/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=aKnS6onh8Ow',
source: 'manual',
},
{
title: 'Papal Hymn: Hymn of the Virtues (Ϯⲙⲏϯ ̀ⲥⲛⲟⲩϯ)',
subtitle: 'Hymns',
category: 'hymns',
videoId: 'aLGm0xlRrX4',
thumbnail: 'https://img.youtube.com/vi/aLGm0xlRrX4/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=aLGm0xlRrX4',
source: 'manual',
},
{
title: 'المتنيح نيافة الأنبا كيرلس (محبة الله فى حياتنا)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'jzIG6cLzms4',
thumbnail: 'https://img.youtube.com/vi/jzIG6cLzms4/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=jzIG6cLzms4',
source: 'manual',
},
{
title: 'نيافة الأنبا أنطونيوس (بيوتنا فى خطر)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'guzauKOpVsU',
thumbnail: 'https://img.youtube.com/vi/guzauKOpVsU/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=guzauKOpVsU',
source: 'manual',
},
{
title: 'نيافة الأنبا أنطونيوس (أما أنا و بيتي فنعبد الرب)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'aHWZQ_bf6Hs',
thumbnail: 'https://img.youtube.com/vi/aHWZQ_bf6Hs/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=aHWZQ_bf6Hs',
source: 'manual',
},
{
title: 'نيافة الأنبا أنطونيوس (أسئلة و أجوبة)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'Sza56WxHZH8',
thumbnail: 'https://img.youtube.com/vi/Sza56WxHZH8/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=Sza56WxHZH8',
source: 'manual',
},
{
title: 'نيافة الأنبا يوسف (التذمر و الشكر)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 's_Ych5MAW-o',
thumbnail: 'https://img.youtube.com/vi/s_Ych5MAW-o/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=s_Ych5MAW-o',
source: 'manual',
},
{
title: 'نيافة الأنبا يوسف (الغضب)',
subtitle: 'Sermon',
category: 'sermons',
videoId: '-V_zR6GJtjY',
thumbnail: 'https://img.youtube.com/vi/-V_zR6GJtjY/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=-V_zR6GJtjY',
source: 'manual',
},
{
title: 'نيافة الأنبا يوسف (من له أذنان للسمع فليسمع)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'j1oHqkSOZLM',
thumbnail: 'https://img.youtube.com/vi/j1oHqkSOZLM/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=j1oHqkSOZLM',
source: 'manual',
},
{
title: 'نيافة الأنبا يوسف (كلمة ربنا فى حياتك)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'oAaOtoQK4sE',
thumbnail: 'https://img.youtube.com/vi/oAaOtoQK4sE/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=oAaOtoQK4sE',
source: 'manual',
},
{
title: 'نيافة الأنبا يوسف (التوبة و أهل نينوى)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'eBuLX8cBn2Y&t=330s',
thumbnail: 'https://img.youtube.com/vi/5S0_xuEh3MI/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=eBuLX8cBn2Y&t=330s',
source: 'manual',
},
{
title: 'نيافة الأنبا يوسف (إيمان انتقائي)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'LBvgfgQbjMM',
thumbnail: 'https://img.youtube.com/vi/LBvgfgQbjMM/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=LBvgfgQbjMM',
source: 'manual',
},
{
title: 'نيافة الأنبا يوسف (من المعاناة إلى المجد)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'Bh1N2f1jQlM',
thumbnail: 'https://img.youtube.com/vi/Bh1N2f1jQlM/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=Bh1N2f1jQlM',
source: 'manual',
},
{
title: 'His Eminence Metropolitan Youssef (God Desires Your Participation)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'ixPy1pv1Ah8',
thumbnail: 'https://img.youtube.com/vi/ixPy1pv1Ah8/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=ixPy1pv1Ah8',
source: 'manual',
},
{
title: 'His Eminence Metropolitan Youssef (The True Christian Doctrine)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'vJpmYEyLKt8',
thumbnail: 'https://img.youtube.com/vi/vJpmYEyLKt8/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=vJpmYEyLKt8',
source: 'manual',
},
{
title: 'His Eminence Metropolitan Youssef (Qualities of True Disciples)',
subtitle: 'Sermon',
category: 'sermons',
videoId: '7j2ZY3PSies',
thumbnail: 'https://img.youtube.com/vi/7j2ZY3PSies/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=7j2ZY3PSies',
source: 'manual',
},
{
title: 'His Eminence Metropolitan Youssef (Stewardship)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'PuPpwMM1ibc',
thumbnail: 'https://img.youtube.com/vi/PuPpwMM1ibc/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=PuPpwMM1ibc',
source: 'manual',
},
{
title: 'His Eminence Metropolitan Youssef (Introduction to the Book of Proverbs)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'tlo-GYO4JHc',
thumbnail: 'https://img.youtube.com/vi/tlo-GYO4JHc/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=tlo-GYO4JHc',
source: 'manual',
},
{
title: 'His Eminence Metropolitan Youssef (The Gospel of St. Matthew: Chapter 19)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'Pke_LZQpxYM',
thumbnail: 'https://img.youtube.com/vi/Pke_LZQpxYM/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=Pke_LZQpxYM',
source: 'manual',
},
{
title: 'His Eminence Metropolitan Youssef (The Gospel of St. John: Chapter 5:31-47)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'hSErC2emAsI',
thumbnail: 'https://img.youtube.com/vi/hSErC2emAsI/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=hSErC2emAsI',
source: 'manual',
},
{
title: 'نيافة الأنبا تكلا (الفرح)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'T4jIOme-DCU',
thumbnail: 'https://img.youtube.com/vi/T4jIOme-DCU/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=T4jIOme-DCU',
source: 'manual',
},
{
title: 'نيافة الأنبا رافائيل (سر التناول)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'O-oQYhPWfOc',
thumbnail: 'https://img.youtube.com/vi/O-oQYhPWfOc/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=O-oQYhPWfOc',
source: 'manual',
},
{
title: 'نيافة الأنبا رافائيل (أختيار المسيح لتلاميذه) | الجزء الأول',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'i6_RGwhLVcw',
thumbnail: 'https://img.youtube.com/vi/i6_RGwhLVcw/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=i6_RGwhLVcw',
source: 'manual',
},
{
title: 'نيافة الأنبا رافائيل (أختيار المسيح لتلاميذه) | الجزء الثانى',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'rp7wO3LfxGI',
thumbnail: 'https://img.youtube.com/vi/rp7wO3LfxGI/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=rp7wO3LfxGI',
source: 'manual',
},
{
title: 'نيافة الأنبا رافائيل (أختيار المسيح لتلاميذه) | الجزء الثالث',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'cThasdSDWZ0',
thumbnail: 'https://img.youtube.com/vi/cThasdSDWZ0/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=cThasdSDWZ0',
source: 'manual',
},
{
title: 'نيافة الأنبا رافائيل (الخلاص بصلب و قيامة المسيح)',
subtitle: 'Sermon',
category: 'sermons',
videoId: '3R5VUwQOpZQ',
thumbnail: 'https://img.youtube.com/vi/3R5VUwQOpZQ/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=3R5VUwQOpZQ',
source: 'manual',
},
{
title: 'نيافة الأنبا مكاريوس (مزمور التوبة)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'jVAXT3orZnU',
thumbnail: 'https://i.postimg.cc/pdx634mH/Anba-Macarius.png',
watchUrl: 'https://www.youtube.com/watch?v=jVAXT3orZnU',
source: 'manual',
},
{
title: 'نيافة الأنبا ميخائيل (اجعلوا قلوبكم على طرقكم)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'BG831nKMWlE',
thumbnail: 'https://img.youtube.com/vi/BG831nKMWlE/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=BG831nKMWlE&t=5098s',
source: 'manual',
},
{
title: 'نيافة الأنبا أبراهام (القيامة دعوة إلى التوبة)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'UKpyPIYcqhA',
thumbnail: 'https://i.postimg.cc/CLR5f6Mj/Anba-Abraham.png',
watchUrl: 'https://www.youtube.com/watch?v=UKpyPIYcqhA',
source: 'manual',
},
{
title: 'نيافة الأنبا بيتر (التواضع في القديسين)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'O6p4E2LJQ4Q',
thumbnail: 'https://i.postimg.cc/TwnSSxc0/Bishop-Peter.png',
watchUrl: 'https://www.youtube.com/watch?v=O6p4E2LJQ4Q',
source: 'manual',
},
{
title: 'القمص داود لمعي (عائلة نوح)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'twtdCWXPR5w',
thumbnail: 'https://img.youtube.com/vi/twtdCWXPR5w/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=twtdCWXPR5w',
source: 'manual',
},
{
title: 'القمص بولس چورچ (التوبة و فحص الضمير)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'e-pCREAGm8U',
thumbnail: 'https://img.youtube.com/vi/e-pCREAGm8U/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=e-pCREAGm8U',
source: 'manual',
},
{
title: 'القمص يوأنس ساروفيم (المحبة في الأسرة المسيحية)',
subtitle: 'Sermon',
category: 'sermons',
videoId: '9r8AoAlZQUQ',
thumbnail: 'https://img.youtube.com/vi/9r8AoAlZQUQ/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=9r8AoAlZQUQ',
source: 'manual',
},
{
title: 'القمص يوأنس ساروفيم (الفرح في الأسرة المسيحية)',
subtitle: 'Sermon',
category: 'sermons',
videoId: '37JygWGmA_k',
thumbnail: 'https://img.youtube.com/vi/37JygWGmA_k/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=37JygWGmA_k',
source: 'manual',
},
{
title: 'القمص يوأنس ساروفيم (السلام في الأسرة المسيحية) | الجزء الأول',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'q9UL1F7LT_w',
thumbnail: 'https://img.youtube.com/vi/q9UL1F7LT_w/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=q9UL1F7LT_w',
source: 'manual',
},
{
title: 'القمص يوأنس ساروفيم (السلام في الأسرة المسيحية) | الجزء الثاني',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'Cpb6iB7xkbg',
thumbnail: 'https://img.youtube.com/vi/Cpb6iB7xkbg/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=Cpb6iB7xkbg',
source: 'manual',
},
{
title: 'القمص يوأنس ساروفيم (السلام في الأسرة المسيحية) | الجزء الثالث',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'SLjJTfkAwhc',
thumbnail: 'https://img.youtube.com/vi/SLjJTfkAwhc/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=SLjJTfkAwhc',
source: 'manual',
},
{
title: 'القمص يوأنس ساروفيم (طول الأناة في الأسرة المسيحية)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 't-YTJWKMLUY',
thumbnail: 'https://img.youtube.com/vi/t-YTJWKMLUY/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=t-YTJWKMLUY',
source: 'manual',
},
{
title: 'القمص يوأنس ساروفيم (اللطف في الأسرة المسيحية) | الجزء الأول',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'olrq-H1gaGk',
thumbnail: 'https://img.youtube.com/vi/olrq-H1gaGk/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=olrq-H1gaGk',
source: 'manual',
},
{
title: 'القمص يوأنس ساروفيم (اللطف في الأسرة المسيحية) | الجزء الثاني',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'XyA9fO-_2i0',
thumbnail: 'https://img.youtube.com/vi/XyA9fO-_2i0/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=XyA9fO-_2i0',
source: 'manual',
},
{
title: 'القمص يوأنس ساروفيم (الصلاح في الأسرة المسيحية) | الجزء الأول',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'FLbpeEcfez4',
thumbnail: 'https://img.youtube.com/vi/FLbpeEcfez4/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=FLbpeEcfez4',
source: 'manual',
},
{
title: 'القمص يوأنس ساروفيم (الصلاح في الأسرة المسيحية) | الجزء الثاني',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'yrxB0S0Rj2M',
thumbnail: 'https://img.youtube.com/vi/yrxB0S0Rj2M/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=yrxB0S0Rj2M',
source: 'manual',
},
{
title: 'القمص يوأنس ساروفيم (الصلاح في الأسرة المسيحية) | الجزء الثالث',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'bI1ZqtZLwCY',
thumbnail: 'https://img.youtube.com/vi/bI1ZqtZLwCY/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=bI1ZqtZLwCY',
source: 'manual',
},
{
title: 'القمص يوأنس ساروفيم (الإيمان في الأسرة المسيحية) | الجزء الأول',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'xTHrZkn8WvI',
thumbnail: 'https://img.youtube.com/vi/xTHrZkn8WvI/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=xTHrZkn8WvI',
source: 'manual',
},
{
title: 'القمص يوأنس ساروفيم (الإيمان في الأسرة المسيحية) | الجزء الثاني',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'Lyj4XnvseVs',
thumbnail: 'https://img.youtube.com/vi/Lyj4XnvseVs/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=Lyj4XnvseVs',
source: 'manual',
},
{
title: 'القمص يوأنس ساروفيم (الإيمان في الأسرة المسيحية) | الجزء الثالث',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'OTn65ueEPTE',
thumbnail: 'https://img.youtube.com/vi/OTn65ueEPTE/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=OTn65ueEPTE',
source: 'manual',
},
{
title: 'القمص يوأنس ساروفيم (الإيمان في الأسرة المسيحية) | الجزء الرابع',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'LLoXIJrk2LA',
thumbnail: 'https://img.youtube.com/vi/LLoXIJrk2LA/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=LLoXIJrk2LA',
source: 'manual',
},
{
title: 'القمص يوأنس ساروفيم (الوداعة في الأسرة المسيحية) | الجزء الأول',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'exR38FOZYxE',
thumbnail: 'https://img.youtube.com/vi/exR38FOZYxE/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=exR38FOZYxE',
source: 'manual',
},
{
title: 'القمص يوأنس ساروفيم (الوداعة في الأسرة المسيحية) | الجزء الثاني',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'd5j6wDzs0ic',
thumbnail: 'https://img.youtube.com/vi/d5j6wDzs0ic/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=d5j6wDzs0ic',
source: 'manual',
},
{
title: 'القمص يوأنس ساروفيم (الوداعة في الأسرة المسيحية) | الجزء الثالث',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'qwEgkoSQcss',
thumbnail: 'https://img.youtube.com/vi/qwEgkoSQcss/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=qwEgkoSQcss',
source: 'manual',
},
{
title: 'القمص يوأنس ساروفيم (الوداعة في الأسرة المسيحية) | الجزء الرابع',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'szVOvRq-IWQ',
thumbnail: 'https://img.youtube.com/vi/szVOvRq-IWQ/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=szVOvRq-IWQ',
source: 'manual',
},
{
title: 'القمص يوأنس ساروفيم (التعفف في الأسرة المسيحية) | الجزء الأول',
subtitle: 'Sermon',
category: 'sermons',
videoId: '1-_0vwdMKFg',
thumbnail: 'https://img.youtube.com/vi/1-_0vwdMKFg/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=1-_0vwdMKFg',
source: 'manual',
},
{
title: 'القمص يوأنس ساروفيم (التعفف في الأسرة المسيحية) | الجزء الثاني',
subtitle: 'Sermon',
category: 'sermons',
videoId: '9WFh1BUV_VY',
thumbnail: 'https://img.youtube.com/vi/9WFh1BUV_VY/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=9WFh1BUV_VY',
source: 'manual',
},
{
title: 'القمص يوأنس ساروفيم (التعفف في الأسرة المسيحية) | الجزء الثالث',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'LFiHJ1H-7l0',
thumbnail: 'https://img.youtube.com/vi/LFiHJ1H-7l0/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=LFiHJ1H-7l0',
source: 'manual',
},
{
title: 'القمص يوأنس ساروفيم (التعفف في الأسرة المسيحية) | الجزء الرابع',
subtitle: 'Sermon',
category: 'sermons',
videoId: '21j_syRavBg',
thumbnail: 'https://img.youtube.com/vi/21j_syRavBg/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=21j_syRavBg',
source: 'manual',
},
{
title: 'القمص بطرس بطرس (ترتيب الأيقونات في الكنيسة و حياة القديس مار مرقس الرسول)',
subtitle: 'Sermon',
category: 'sermons',
videoId: '2391_iUZ-dU&t=2677s',
thumbnail: 'https://img.youtube.com/vi/2391_iUZ-dU/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=2391_iUZ-dU&t=2677s',
source: 'manual',
},
{
title: 'Fr. Boutros Boutros: Prepare a Good Land for the Word of God',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'oG0vyAYxJSU',
thumbnail: 'https://img.youtube.com/vi/oG0vyAYxJSU/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=oG0vyAYxJSU',
source: 'manual',
},
{
title: 'Fr. Kyrillos Zaki: Sanctify a Fast (Servants Meeting)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'tAQ_2q0CfFY&t=725s',
thumbnail: 'https://img.youtube.com/vi/tAQ_2q0CfFY/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=tAQ_2q0CfFY&t=725s',
source: 'manual',
},
{
title: 'Fr. Kyrillos Zaki: History of the Divine Liturgy (Servants Meeting)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'xq1jYwH1wHw&t=360s',
thumbnail: 'https://img.youtube.com/vi/xq1jYwH1wHw/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=xq1jYwH1wHw&t=360s',
source: 'manual',
},
{
title: 'القمص إڤرايم ميخائيل (معجزات عن مار مينا)',
subtitle: 'Sermon',
category: 'sermons',
videoId: '1h_H3R1TqfI&t=185s',
thumbnail: 'https://img.youtube.com/vi/1h_H3R1TqfI/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=1h_H3R1TqfI&t=185s',
source: 'manual',
},
{
title: 'القس تادرس هيرمينا (الفرح)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'OUUJhVq9A1I',
thumbnail: 'https://img.youtube.com/vi/OUUJhVq9A1I/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=OUUJhVq9A1I',
source: 'manual',
},
{
title: 'القس تادرس هيرمينا (التفكير الايجابي)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'ZKIr4yzIJk8',
thumbnail: 'https://img.youtube.com/vi/ZKIr4yzIJk8/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=ZKIr4yzIJk8',
source: 'manual',
},
{
title: 'القس دانيال إبراهيم (أهمية دور الأب في الاسرة)',
subtitle: 'Sermon',
category: 'sermons',
videoId: 'UJOIQsBdtyE',
thumbnail: 'https://img.youtube.com/vi/UJOIQsBdtyE/hqdefault.jpg',
watchUrl: 'https://www.youtube.com/watch?v=UJOIQsBdtyE',
source: 'manual',
},
];